#!usr/bin/python3

import cv2

#starting camera
cap=cv2.VideoCapture(1)

while cap.isOpened() :
  status,frame=cap.read()

  cv2.imshow('live',frame)
  if cv2.waitKey(10) &. 0xff ==ord('q') :
    break
  
  #cv2.destroyWindow('live')
  cv2.destroyAllwindows(). #this will destroy all windows 
  
  # to close camera
  cap.release()
  
