#!/usr/bin/python3

import cv2
#starting camera
cap=cv2.VideoCapture(0)
#adding plugin
plugin=cv2.Videowriter_fourcc(*'XVID')
3#saving video
cv2.VideoWriter('class.mp4',plugin,20)


while cap.isOpened() :
  status,frame=cap.read()
  
  
cv2.imshow('live',frame)
  if cv2.waitKey(10). & 0xff == ord('q'):
  break
cv2.destroyAllWIndows()
cap.release()
